const PREFIX = "SMART";

export const REQUEST_COUNTRY_NAME_LOAD= `${PREFIX}REQUEST_COUNTRY_NAME_LOAD`;
export const RECEIVE_COUNTRY_NAME_LOAD = `${PREFIX}RECEIVE_COUNTRY_NAME_LOAD`;

export const REQUEST_ADD_COUNTRY_NAME= `${PREFIX}REQUEST_ADD_COUNTRY_NAME`;
export const RECEIVE_ADD_COUNTRY_NAME = `${PREFIX}RECEIVE_ADD_COUNTRY_NAME`;